#!/bin/sh

# reset main repo, but leave node_modules_cache untouched for ci caching
git clean -ffdxe node_modules_cache

# remove git hooks generated by lint-staged
rm -rf .git/hooks

# reset submodules
for sm in externals/*
  do (cd "$sm" && git clean -ffdx) || continue
  done
