#import '../user-fragment'

fragment DsCommonCodeValueMappingFields on DsCommonCodeValueMapping {
  id
  codeMappingId
  codeValueId
  codeValue
  codeValueName
  value
  code
  creator {
    ...UserFields
  }
  modifier {
    ...UserFields
  }
  createTm
  modifyTm
}
