#import '../user-fragment'

fragment DsCommonCodeValueFields on DsCommonCodeValue {
  id
  value
  cnName
  enName
  description
  creator {
    ...UserFields
  }
  modifier {
    ...UserFields
  }
  createTm
  modifyTm
}
