#import '../user-fragment'

fragment DqsIssueHistoryFields on DqsIssueHistory {
  name
  operation
  transact {
    ...UserFields
  }
  startDate
  endDate
  durationInMillis
  opinion
  handleStateEnum
}
