# 机构清单
fragment DsInstitutional on DsInstitutional {
  # 主键ID
  id
  #父节点ID
  pid
  # 标准ID
  standardId
  # 编号
  numberId
  # 中文名称
  cnName
  # 英文名称
  enName
  # 机构描述
  description
  # 英文简写
  enShorthand
  # 英文简写编码
  enShorthandCoding
  # 是否有子节点
  hasChildren
}
